### PR TITLE
travis-ci: run javadoc linter with travis

### LINKED ISSUE #244: build: run javadoc linter in local testing and CI
I recently found that I'm unable to prepare a release (`mvn release:clean release:prepare -DpushChanges=false`) because of javadoc linter errors (see PR #243). It would be good to catch those errors (and also warnings) during development.

I don't know how to run a javadoc linter separately from `release:prepare`. Maybe we need to extract necessary parts of oss-parent POM to our POM file: if so, this issue looks connected with #241.

### PR DESCRIPTION
**Pull request by Artyomcool**
It should help to fix javadoc issues much early then during mvn release:clean release:prepare.

Fixes #244

### CODE REVIEW

**Review by Totktonada — COMMENTED** [review]
Nice to see new contributors!

Several minor comments re processes:

* Please, sink down `Fixes #xxx` to the end of the commit message (see [examples](https://www.tarantool.io/en/doc/1.10/dev_guide/developer_guidelines/#how-to-write-a-commit-message)). Personally I feel placing links, issue number and other metainformation within a subject line as bad practice: the subject line has very restricted length (usually softly limited to 50 symbols), but should be as descriptive as possible.
* We usually use prefixes to ease distinguish changes around tests, CI, a particular code subsystem, no-behaviour-changes refactoring. There is no restricted set of such prefixes, but for CI changes I usually use 'travis-ci: ' (where Travis-CI is used).

**Comment by Artyomcool** [comment]
fixed!

**Comment by Totktonada** [comment]
tarantool-2.4 and tarantool-2.5 fails are due to https://github.com/tarantool/tarantool/issues/4507, it is unrelated. I'll fix soon.

**Review by Totktonada — APPROVED** [review]
LGTM.

**Comment by Totktonada** [comment]
> tarantool-2.4 and tarantool-2.5 fails are due to [tarantool/tarantool#4507](https://github.com/tarantool/tarantool/issues/4507), it is unrelated. I'll fix soon.

Fixed in PR #256, but the next CI fail reveals (see comments). I'll leave CI red for a while: don't have enough attentiveness tonight :)

**Pull request merged**
